### ISSUE TITLE
Multiple maps on a page?

### ISSUE THREAD

**Issue by mhkeller** [propublica/landline#6]
It looks as though there are a few id's sprinkled around (here's one: https://github.com/propublica/landline/blob/master/public/javascripts/landline.stateline.js#L75) that would make multiple map instances on a page problematic. 

Could this be fixable? 
![th](https://cloud.githubusercontent.com/assets/498744/5710765/d08033ce-9a72-11e4-9fb6-a99394cdf091.jpg)

**Comment by sisiwei** [comment]
Hey @mhkeller, here's a live demo of multiple maps per page: https://propublica.github.io/landline/demo-multiple-maps.html

I'm essentially using the container as a unique ID that attaches to each of the divs we create. Seemed like the easiest solution since Raphael wants an ID specifically. Lemme know if you have any trouble.

**Comment by mhkeller** [comment]
Awessommmmmmeee!
